drivers/dahdi: fix MAX redefine
Fix for this error with linux v6.11-rc2:

  CC [M]  oct612x/octdeviceapi/oct6100api/oct6100_api/oct6100_channel.o
wctdm24xxp/base.c: In function 'wait_access':
wctdm24xxp/base.c:1504: error: "MAX" redefined [-Werror]
 1504 |         #define MAX 10 /* attempts */
      |
In file included from /linux/include/linux/kernel.h:28,
                 from wctdm24xxp/base.c:41:
/linux/include/linux/minmax.h:330: note: this is the location of the previous definition
  330 | #define MAX(a,b) __cmp(max,a,b)

Related: linux 1a251f52 ("minmax: make generic MIN() and MAX() macros available everywhere")
Change-Id: If048523ac2c69b1251fdee758a2cd3e14f8e617c