frame_fifo: add missing declaration
/build/drivers/dahdi/trunkdev/frame_fifo.c:32:6: error: no previous prototype for 'fifo_dump' [-Werror=missing-prototypes]
   32 | void fifo_dump(struct frame_fifo *fifo)
      |      ^~~~~~~~~
cc1: all warnings being treated as errors

Change-Id: I02eccb9c404157352d6c317b02d742b90c229deb