drivers/dahdi/wct4xxp: fix inline not at beginning
Fix for this error with linux v6.10-rc1:

wct4xxp/base.c:1157:1: error: 'inline' is not at beginning of declaration [-Werror=old-style-declaration]
 1157 | static void inline t4_hdlc_xmit_fifo(struct t4 *wc, unsigned int span, struct t4_span *ts)
      | ^~~~~~

Related: linux f5982cce ("kbuild: turn on -Wextra by default")
Change-Id: Ic77d94271e7844ea2e06ccd001156d90f321367e